# Generated by Django 2.0.7 on 2018-10-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='member_count',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='成员数量'),
        ),
        migrations.AlterField(
            model_name='team',
            name='notes',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.Note', verbose_name='文献'),
        ),
    ]
