# Generated by Django 2.0.7 on 2018-10-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20181030_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='doi',
            field=models.CharField(default=1, max_length=128, verbose_name='数字对象唯一标识符'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='institution',
            field=models.CharField(default=1, max_length=128, verbose_name='机构'),
            preserve_default=False,
        ),
    ]
