# Generated by Django 2.0.7 on 2018-10-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20181031_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='QNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('authors', models.CharField(max_length=128, verbose_name='作者')),
                ('quotes', models.IntegerField(verbose_name='被引量')),
                ('sore_year', models.IntegerField(verbose_name='发表年度')),
                ('url', models.CharField(max_length=256, verbose_name='链接')),
            ],
            options={
                'verbose_name': '引用文献',
                'verbose_name_plural': '引用文献',
                'ordering': ['title'],
                'get_latest_by': 'title',
            },
        ),
        migrations.AddField(
            model_name='note',
            name='quotes',
            field=models.ManyToManyField(related_name='quoted', to='mainapp.QNote', verbose_name='参考文献'),
        ),
    ]
