# Generated by Django 2.0.7 on 2018-10-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20181031_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='qnote',
            name='institution',
            field=models.CharField(default=1, max_length=128, verbose_name='机构'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qnote',
            name='url',
            field=models.CharField(max_length=512, verbose_name='链接'),
        ),
    ]
