# Generated by Django 2.0.7 on 2018-11-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_team_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='introduce',
            field=models.CharField(default=1, max_length=1024, verbose_name='介绍'),
            preserve_default=False,
        ),
    ]
