# Generated by Django 2.0.7 on 2018-11-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_team_introduce'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='notes_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='文献数量'),
        ),
    ]
