# Generated by Django 2.0.7 on 2018-11-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_team_notes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='introduce',
            field=models.TextField(max_length=1024, verbose_name='介绍'),
        ),
    ]
