# Generated by Django 2.0.7 on 2018-11-06 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_user_priv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_priv',
            options={'verbose_name': '用户私有文献组', 'verbose_name_plural': '用户私有文献组'},
        ),
        migrations.AlterField(
            model_name='note',
            name='quotes',
            field=models.ManyToManyField(blank=True, null=True, related_name='quotes', to='mainapp.QNote', verbose_name='参考文献'),
        ),
        migrations.AlterField(
            model_name='note',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Source', verbose_name='来源'),
        ),
    ]
