# Generated by Django 2.0.7 on 2018-11-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20181106_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='upfile',
            field=models.FileField(blank=True, null=True, upload_to='upload/%Y/%m/%d/'),
        ),
    ]
