# Generated by Django 2.0.7 on 2018-11-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_note_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='ontop',
            field=models.BooleanField(default=True, verbose_name='是否置顶'),
        ),
        migrations.AlterField(
            model_name='note',
            name='show',
            field=models.BooleanField(default=True, verbose_name='是否显示'),
        ),
    ]
